# Generated by Django 2.2.2 on 2019-08-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FilePathField(path='/Users/htdutchy/PycharmProjects/markdown_blog/upload/', recursive=True, unique=True)),
                ('fileType', models.CharField(max_length=24)),
                ('altText', models.CharField(blank=True, max_length=120, null=True)),
                ('cachedSmall', models.FilePathField(path='/Users/htdutchy/PycharmProjects/markdown_blog/web/static/', recursive=True)),
                ('cachedMedium', models.FilePathField(path='/Users/htdutchy/PycharmProjects/markdown_blog/web/static/', recursive=True)),
                ('cachedLarge', models.FilePathField(path='/Users/htdutchy/PycharmProjects/markdown_blog/web/static/', recursive=True)),
                ('fileHash', models.CharField(max_length=160)),
                ('lastCached', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TagCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.FilePathField(allow_files=False, allow_folders=True, path='/Users/htdutchy/PycharmProjects/markdown_blog/upload/', unique=True)),
                ('file', models.FilePathField(path='/Users/htdutchy/PycharmProjects/markdown_blog/upload/', recursive=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('fileHash', models.CharField(max_length=160)),
                ('lastCached', models.DateTimeField()),
                ('featureImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_cache.ImageCache')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FilePathField(path='/Users/htdutchy/PycharmProjects/markdown_blog/upload/', recursive=True, unique=True)),
                ('fileHash', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=240)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField()),
                ('author', models.CharField(blank=True, max_length=120, null=True)),
                ('cachedHeading', models.CharField(max_length=240)),
                ('cachedContent', models.TextField()),
                ('draft', models.BooleanField()),
                ('lastCached', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog_cache.CategoryCache')),
                ('featureImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_cache.ImageCache')),
                ('tags', models.ManyToManyField(to='blog_cache.TagCache')),
            ],
            options={
                'unique_together': {('slug', 'category')},
            },
        ),
    ]
