# Generated by Django 3.0.2 on 2020-01-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_cache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecache',
            name='file',
            field=models.FilePathField(path='/home/htdutchy/PycharmProjects/markdown-blog/upload/', recursive=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categorycache',
            name='file',
            field=models.FilePathField(path='/home/htdutchy/PycharmProjects/markdown-blog/upload/', recursive=True),
        ),
        migrations.AlterField(
            model_name='categorycache',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/home/htdutchy/PycharmProjects/markdown-blog/upload/', unique=True),
        ),
        migrations.AlterField(
            model_name='imagecache',
            name='cachedLarge',
            field=models.FilePathField(path='/home/htdutchy/PycharmProjects/markdown-blog/web/static/', recursive=True),
        ),
        migrations.AlterField(
            model_name='imagecache',
            name='cachedMedium',
            field=models.FilePathField(path='/home/htdutchy/PycharmProjects/markdown-blog/web/static/', recursive=True),
        ),
        migrations.AlterField(
            model_name='imagecache',
            name='cachedSmall',
            field=models.FilePathField(path='/home/htdutchy/PycharmProjects/markdown-blog/web/static/', recursive=True),
        ),
        migrations.AlterField(
            model_name='imagecache',
            name='file',
            field=models.FilePathField(path='/home/htdutchy/PycharmProjects/markdown-blog/upload/', recursive=True, unique=True),
        ),
    ]
