# Generated by Django 3.0.2 on 2020-01-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_cache', '0002_auto_20200112_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecache',
            name='extraData',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagecache',
            name='exifData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
