# Generated by Django 3.0.2 on 2020-02-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_cache', '0003_auto_20200119_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecache',
            name='isPortrait',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
